# Color, Fonds

#DIMENTIONS
APP_WIDTH: int = 250
APP_HEIGHT: int = 500

#COlORS
LIGHT_GRAY = "#F5F5F5"
LABEL_COLOR = "#25265E"
OFF_WIGHT_COLOR = "#F8FAFF"
LIGHT_BLUE = "#CCEDFF"

#FONTS
DEFAULT_FONT = ("arial", 20)
SMALL_FONT = ("araial" , 15)
BIG_FONT = ("arial", 20, "bold")
BUTTONS_FONT = ("arial", 24, "bold")

#Symbol
OPEN_SQRT_CONFIG_TEXT = "\u221ax"
OPEN_CURT_CONFIG_TEXT = "∛x"
OPEN_SQRT_EXPRESSION = "\u221a"
OPEN_CURT_EXPRESSION = "∛"
CLOSE_ROOT_EXPRESSION = "'"
CLOSE_ROOT_CONFIG_TEXT = "x'"