WORDS: list[str] = ["Tina",
"apple", "banana", "cat", "dog", "elephant", "flower", "guitar", "house", "jacket", "kite", "lemon",
"mountain", "notebook", "orange", "penguin", "queen", "rainbow", "sun", "tree", "umbrella", "violin",
"water", "xylophone", "yacht", "zebra", "airplane", "book", "car", "dance", "egg", "fish", "game", "hat",
"island", "juice", "key", "lamp", "moon", "nest", "ocean", "pizza", "quilt", "robot", "star", "table",
"unicorn", "vase", "window", "yarn", "ant", "bear", "cloud", "drum", "eagle", "fox", "grass", "horse",
"insect", "jelly", "kiwi", "leaf", "mouse", "nut", "owl", "parrot", "quokka", "rose", "snake", "turtle",
"umbrella", "volcano", "whale", "x-ray", "yo-yo", "zipper", "almond", "bread", "cucumber", "doughnut",
"eggplant", "fig", "grape", "honey", "iceberg", "jellyfish", "kiwi", "lollipop", "mushroom", "noodle",
"olive", "pancake", "quinoa", "radish", "spinach", "tofu", "turnip", "vanilla", "waffle", "zucchini",
"adventure", "bicycle", "candle", "dolphin", "elephant", "feather", "giraffe", "horizon", "igloo",
"jungle", "kettle", "lighthouse", "mosaic", "nectar", "octopus", "pyramid", "quasar", "robot", "sapphire",
"telescope", "universe", "vortex", "whisper", "xenon", "yarn", "zodiac", "artichoke", "butterfly", "cactus",
"daisy", "eclipse", "fountain", "goblet", "hammock", "ink", "jigsaw", "kaleidoscope", "lunar", "mystery",
"ninja", "oasis", "puzzle", "quilt", "raccoon", "symphony", "tulip", "ukulele", "village", "wisteria", 
"xylophonist", "yeti", "zinnia""apple", "banana", "orange", "grape", "cherry", "mango", "peach", "lemon", "pear", "plum",
"table", "chair", "couch", "shelf", "desk", "lamp", "mirror", "window", "door", "carpet",
"house", "apartment", "cabin", "castle", "garage", "garden", "kitchen", "bedroom", "bathroom", "roof",
"dog", "cat", "rabbit", "horse", "elephant", "lion", "tiger", "monkey", "giraffe", "zebra",
"ocean", "river", "lake", "pond", "waterfall", "stream", "beach", "island", "shore", "harbor",
"cloud", "rain", "storm", "thunder", "lightning", "snow", "wind", "hurricane", "tornado", "fog",
"music", "guitar", "piano", "violin", "trumpet", "drums", "flute", "saxophone", "song", "melody",
"car", "bus", "bicycle", "motorcycle", "train", "airplane", "helicopter", "boat", "ship", "submarine",
"computer", "keyboard", "mouse", "screen", "laptop", "printer", "speaker", "microphone", "camera", "phone",
"book", "magazine", "newspaper", "novel", "dictionary", "journal", "poem", "story", "letter", "document",
"school", "teacher", "student", "classroom", "homework", "exam", "library", "lesson", "notebook", "pencil",
"fire", "earth", "water", "air", "metal", "wood", "stone", "sand", "glass", "plastic",
"happiness", "sadness", "anger", "fear", "love", "hate", "surprise", "curiosity", "pride", "guilt",
"day", "night", "morning", "afternoon", "evening", "sunrise", "sunset", "midnight", "dawn", "dusk",
"city", "village", "town", "country", "capital", "suburb", "street", "avenue", "square", "market",
"doctor", "nurse", "police", "firefighter", "teacher", "engineer", "scientist", "chef", "pilot", "artist",
"bread", "butter", "cheese", "egg", "meat", "fish", "vegetable", "fruit", "soup", "salad",
"smile", "laugh", "cry", "yawn", "wink", "hug", "kiss", "wave", "shout", "whisper",
"fast", "slow", "big", "small", "tall", "short", "hot", "cold", "bright", "dark",
"jump", "run", "walk", "sit", "stand", "dance", "swim", "climb", "fly", "crawl",
"circle", "square", "triangle", "rectangle", "oval", "cube", "sphere", "pyramid", "diamond", "star",
"simon", "raphael", "michalis", "tina", "dog", "cat", "codemanufaktur", "python", "java"]

LIVES: int = 5